root: true
extends:
  - zakodium/ts
  - zakodium/react
parserOptions:
  project:
    - './tsconfig.json'
    - './tsconfig.node.json'
overrides:
  - files: ['./dump/**/*.{js,ts}']
    env:
      node: true
    rules:
      no-console: off
