name: Update data

on:
  schedule:
    # Run every day at 3:30.
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Get dates for cache
        id: dates
        run: |
          echo "now=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "yesterday=$(date -d 'yesterday' +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Cache data
        uses: actions/cache@v3
        with:
          path: dump/data
          key: ${{ steps.dates.outputs.now }}
          restore-keys: ${{ steps.dates.outputs.yesterday }}
      - name: Update data
        run: |
          cd dump
          node wiki.js ids
          node wiki.js rev
          node wiki.js update
          node wiki.js parse -p
      - name: Commit changes
        run: |
          git config --local user.email "admin@cheminfo.org"
          git config --local user.name "cheminfo bot"
          cp public/data.json site/src/json/data.json
          cp public/smiles.txt site/smiles.txt
          cp public/idcode.txt site/idcode.txt
          git add site/src/json/data.json site/smiles.txt site/idcode.txt
          git add public/data.json public/smiles.txt public/idcode.txt stats.json
          git commit -m "update data" -m "$(tail -2 stats.json | head -1 | jq '.')"
          git push
